### ISSUE TITLE
Opentelemetry

### ISSUE THREAD

**Issue by Geekul** [acester822/LGTMP#7]
Hello, working with Opentelemetry java agent?
Thanks

**Comment by acester822** [comment]
It's not set up for it 100%, but it could be modified to work. Alloy is an otel collector and can use otel components. Also you could look into this, https://grafana.com/docs/grafana-cloud/monitor-applications/application-observability/setup/instrument/java/. I am still apprehensive to go exclusively cloud, but you could configure it locally most likely. I run everything local and then use grafana's pdc connector if I want to play around with their cloud features
